[workspace]
resolver = '2'
members = [
  'server',
  'web',
]

[workspace.package]
license = "BlueOak-1.0.0"
publish = false

[workspace.metadata.bin]
sea-orm-cli = { version = '0.12.14' }
squill = { version = '0.8.0' }
trunk = { version = '0.18.8' }
wasm-pack = { version = '0.12.1' }
