app = 'ebd'
primary_region = 'sjc'

[deploy]
release_command = "squill migrate -vvv --migrations-dir /src/migrations"

[http_service]
processes = ['app']
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
