//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::greetings::Entity as Greetings;
pub use super::jobs::Entity as Jobs;
pub use super::something::Entity as Something;
pub use super::users::Entity as Users;
