[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
gloo = "0.11.0"
thiserror = "1.0.57"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tracing-web = "0.1.3"
wasm-bindgen-futures = "0.4.41"
yew = { version = "0.21.0", features = ["csr"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.41"
